<a href="https://colab.research.google.com/github/SaYaNa1234567/ML/blob/main/behavior.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn. model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

pd.set_option('display.max_columns', None)

In [33]:
df = pd.read_csv('social_media_user_behavior.csv')
df.head()

,user_id,age,gender,country,profession,primary_platform,platforms_used_count,daily_usage_hours,sessions_per_day,avg_session_duration_min,preferred_device,peak_usage_time,followers_count,following_count,posts_per_week,likes_given_per_day,comments_per_day,shares_per_day,dms_sent_per_day,preferred_content_type,scroll_speed,ad_click_rate,purchased_via_social_media,monthly_spend_via_social_usd,primary_purpose,sleep_disruption,self_reported_mental_health_score,screen_time_concern,notification_frequency,privacy_setting,influencer_status,account_join_date,mood_while_scrolling,takes_social_media_breaks
0,USR00001,30,Female,UK,Doctor,Facebook,1,1.6,2,48.0,Smartphone,Late Night (12am+),353,99,1,17,1,3,8,Photos,Medium,0.089,Yes,67.72,Entertainment,No impact,3.9,No,Do Not Disturb,Friends Only,No,2022-10-21,Neutral,No
1,USR00002,25,Male,USA,Entrepreneur,Instagram,2,2.4,5,28.8,Smartphone,Afternoon (12-4pm),276,514,2,28,3,4,16,Memes,Medium,0.065,Yes,1.62,News & Updates,Moderate impact,4.2,No,Selected,Public,No,2024-12-03,Neutral,Yes
2,USR00003,32,Male,UAE,Freelancer,TikTok,5,0.5,6,5.0,Smartphone,Night (9pm-12am),203,422,3,26,4,2,7,Videos,Slow,0.278,No,0.00,Learning,Mild impact,4.8,Yes,Always On,Friends Only,No,2023-03-29,Happy,Yes
3,USR00004,39,Prefer not to say,Pakistan,Other,TikTok,4,3.0,7,25.7,Smartphone,Evening (6-9pm),29083,474,1,16,3,1,12,Entertainment,Fast,0.094,No,0.00,Entertainment,Mild impact,7.9,Somewhat,Always On,Public,Yes,2024-04-26,Happy,No
4,USR00005,25,Male,UK,Other,YouTube,3,3.9,7,33.4,Tablet,Evening (6-9pm),104,197,2,27,7,4,7,Photos,Fast,0.075,No,0.00,Entertainment,Mild impact,6.5,No,Do Not Disturb,Public,No,2023-09-08,Inspired,No

In [34]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

In [46]:
df_original = df.copy()
df_model = df.copy()

encoders = {}
text_columns = []
cols_drop1 = ['user_id']
for col in cols_drop1:
  if col in df_model.columns:
    df_model = df_model.drop(columns=[col])
    if col in df_original.columns:
      df_model = df_original.drop(columns=[col])
for col in df_model.columns:
  if df_model[col].dtype in ['object', 'string']:
    le = LabelEncoder()
    text_columns.append(col)
    df_model[col] = le.fit_transform(df_model[col].astype(str))
    encoders[col] = le

df_model.head()

,age,gender,country,profession,primary_platform,platforms_used_count,daily_usage_hours,sessions_per_day,avg_session_duration_min,preferred_device,peak_usage_time,followers_count,following_count,posts_per_week,likes_given_per_day,comments_per_day,shares_per_day,dms_sent_per_day,preferred_content_type,scroll_speed,ad_click_rate,purchased_via_social_media,monthly_spend_via_social_usd,primary_purpose,sleep_disruption,self_reported_mental_health_score,screen_time_concern,notification_frequency,privacy_setting,influencer_status,account_join_date,mood_while_scrolling,takes_social_media_breaks
0,30,0,8,1,0,1,1.6,2,48.0,3,2,353,99,1,17,1,3,8,4,1,0.089,2,67.72,1,2,3.9,0,1,0,0,243,3,0
1,25,1,9,3,1,2,2.4,5,28.8,3,0,276,514,2,28,3,4,16,2,1,0.065,2,1.62,4,1,4.2,0,3,2,0,901,3,2
2,32,1,7,4,5,5,0.5,6,5.0,3,4,203,422,3,26,4,2,7,7,2,0.278,0,0.00,2,0,4.8,2,0,0,0,379,1,2
3,39,3,6,6,5,4,3.0,7,25.7,3,1,29083,474,1,16,3,1,12,1,0,0.094,0,0.00,1,0,7.9,1,0,2,1,713,1,0
4,25,1,8,6,7,3,3.9,7,33.4,4,1,104,197,2,27,7,4,7,4,0,0.075,0,0.00,1,0,6.5,0,1,2,0,519,2,0

In [44]:
X = df_model
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [47]:
min_samples = max(3, X_scaled.shape[1]*2)
dbscan = DBSCAN(eps = 1.0, min_samples=min_samples)
clusters = dbscan.fit_predict(X_scaled)
df_model['clusters'] = clusters
df_original['clusters'] = clusters