<a href="https://colab.research.google.com/github/SaYaNa1234567/ML/blob/main/zombie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import seaborn as abs
from sklearn.preprocessing import LabelEncoder

In [92]:
label = LabelEncoder()

In [93]:
df = pd.read_csv('student_stress_dataset.csv')
df

     id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
0     1            2            6                   5          55         High
1     2            5            7                   2          75          Low
2     3            1            5                   6          45         High
3     4            4            6                   3          70       Medium
4     5            6            8                   1          85          Low
..  ...          ...          ...                 ...         ...          ...
95   96            3            6                   4          62       Medium
96   97            2            5                   6          49         High
97   98            6            8                   1          89          Low
98   99            4            6                   3          66       Medium
99  100            1            5                   7          41         High

[100 rows x 6 columns]

In [94]:
df.isnull().sum()

id                    0
study_hours           0
sleep_hours           0
social_media_hours    0
exam_score            0
stress_level          0
dtype: int64

In [95]:
df.iloc[-1][['sleep_hours', 'exam_score']]

sleep_hours     5
exam_score     41
Name: 99, dtype: object

In [96]:
df['stress_level'] = label.fit_transform(df['stress_level'])

In [97]:
df

,id,study_hours,sleep_hours,social_media_hours,exam_score,stress_level
0,1,2,6,5,55,0
1,2,5,7,2,75,1
2,3,1,5,6,45,0
3,4,4,6,3,70,2
4,5,6,8,1,85,1
...,...,...,...,...,...,...
95,96,3,6,4,62,2
96,97,2,5,6,49,0
97,98,6,8,1,89,1
98,99,4,6,3,66,2
99,100,1,5,7,41,0

In [98]:
features = ['study_hours', 'sleep_hours','social_media_hours', 'exam_score']

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [101]:
from sklearn.neighbors import KNeighborsClassifier

In [102]:
X = df[features]
y = df['stress_level']
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.2, random_state=42)

In [103]:
models ={
    'LR': LogisticRegression(max_iter=500),
    'SVM': SVC(),
    'tree': DecisionTreeClassifier(),
    'forest': RandomForestClassifier(),
    'nn': KNeighborsClassifier(n_neighbors=3)
}

In [104]:
from sklearn.metrics import accuracy_score
example = np.array([[12, 1, 3, 40]])
example_df = pd.DataFrame(example, columns = features)

In [105]:
for name, model in models.items():
  model.fit(X_train, y_train)
  predictions = model.predict(X_test)
  accuracy = accuracy_score(y_test, predictions)
  print(f"Accuracy of train: {name}: {accuracy:.2f}")
  print(f"Predict: {model.predict(example_df)[0]}")

Accuracy of train: LR: 1.00
Predict: 0
Accuracy of train: SVM: 0.75
Predict: 0
Accuracy of train: tree: 1.00
Predict: 2
Accuracy of train: forest: 1.00
Predict: 0
Accuracy of train: nn: 1.00
Predict: 0